# Ce fichier est le point d'entrée pour configurer vos propres services.
# Les fichiers dans le sous-répertoire packages/ configurent vos dépendances.

# Placez ici les paramètres qui n'ont pas besoin de changer sur chaque machine où l'application est déployée
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.stripe.public_key: '%env(STRIPE_PUBLIC_KEY)%'
    app.stripe.secret_key: '%env(STRIPE_SECRET_KEY)%'
    app.stripe.webhook_secret: '%env(STRIPE_WEBHOOK_SECRET)%'

services:
    # Configuration par défaut pour les services dans *ce* fichier
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances dans vos services.
        autoconfigure: true # Enregistre automatiquement vos services comme commandes, souscripteurs d'événements, etc.
        bind:
            $stripePublicKey: '%app.stripe.public_key%'

    # Rend les classes dans src/ disponibles pour être utilisées comme services
    # Cela crée un service par classe dont l'id est le nom de classe pleinement qualifié
    App\:
        resource: '../src/'

    # Ajoutez plus de définitions de services lorsqu'une configuration explicite est nécessaire
    # Veuillez noter que les dernières définitions *remplacent* toujours les précédentes

    App\Service\MediaUploadService:
        bind:
            $projectDir: '%kernel.project_dir%'

    App\Service\StripeService:
        arguments:
            $stripeSecretKey: '%app.stripe.secret_key%'
            $webhookSecret: '%app.stripe.webhook_secret%'
            
    # Configuration du gestionnaire de webhook Stripe
    App\Controller\StripeWebhookController:
        arguments:
            $webhookSecret: '%app.stripe.webhook_secret%'

    # Alias pour l'authentificateur de formulaire de connexion
    Symfony\Component\Security\Http\Authenticator\FormLoginAuthenticator: '@security.authenticator.form_login.main'
